
// para q no salga tanta etiqueta de error al pepe
rootLogger.level = ERROR
rootLogger.appenderRef.stdout.ref = ConsoleAppender

appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

logger.spark.name = org.apache.spark
logger.spark.level = ERROR

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = ERROR